---
# handlers file for op5-monitor
- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
  become: true

- name: Restart smsd
  service:
    name: smsd
    state: restarted
  become: true

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
  become: true

- name: Display Possible Problems From Installation/Update
  debug:
    msg: "{{ op5_monitor_yum_result.results[0].split('\n') | select('match', '.*(ERRO|Erro|erro|WARN|Warn|warn|FAIL|Fail|fail).*') | list }}"
  listen: "Reboot"

- name: Reboot
  reboot:
    connect_timeout: 20
  when: op5_monitor_state is defined and op5_monitor_state == "installed"
  become: true

- name: Restart postfix
  service:
    name: postfix
    state: restarted
  become: true

- name: Restart synergy
  service:
    name: synergy
    state: restarted
  become: true
