---
- name: Add Smsd Configuration To /etc/smsd.conf
  template:
    src: etc/smsd.conf.j2
    dest: /etc/smsd.conf
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: "Restart smsd"
  when: op5_smsd_device is defined and op5_smsd_device|length
  become: true
